kafka:
  user-audit:
    consumer:
      topic-name: TestTopic
      group-id: useraudit.notification.local


spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: notificationedj@gmail.com
      password: 0208@notificationservice
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true





